// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// noinspection SpellCheckingInspection

import { env } from './.env';

export const environment = {
  production: true, // has to behave like production
  hmr: false,
  version: env.npm_package_version,
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  firebase: {
    emulator: {
      active: env.USE_BACKEND_EMULATOR == 'Yes',
      authURL: 'http://localhost:9099',
      firestoreURL: {
        host: 'localhost',
        port: 8080
      },
      functionsURL: {
        host: 'localhost',
        port: 5001
      }
    },
    apiKey: env.FIREBASE_API_KEY,
    authDomain: 'rozgar-today.firebaseapp.com',
    databaseURL: 'https://rozgar-today.firebaseio.com',
    projectId: 'rozgar-today',
    storageBucket: 'rozgar-today.appspot.com',
    messagingSenderId: '712869014206',
    appId: '1:712869014206:web:f50f15e740eb256e450cef',
    measurementId: 'G-C5170PLTS4'
  },
  stripe: {
    publishableKey:
      'pk_test_51JJXVXSJUFAUz58Xee7OBE51NHS3JKbP3O2qupHY6EI1ftDZDGL7qnqsq1rGnwuTCS1t44Km8xKCRt4aAFoQsbC900470w0lDw'
  }
};
