name: Build (Beta)

on:
  push:
    branches: [beta]

jobs:
  main:
    name: Test, Deploy & Pre-Release
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: Beta
      url: https://beta.rozgar.today
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2
        if: ${{ !contains(github.event.head_commit.message, 'chore(release)') || !contains(github.event.head_commit.message, '-beta.') }}
        with:
          ref: beta
          token: ${{ secrets.ACTIONS_TOKEN }}
          fetch-depth: 0

      - name: Install
        if: ${{ !contains(github.event.head_commit.message, 'chore(release)') || !contains(github.event.head_commit.message, '-beta.') }}
        run: npm install

      - name: Check Linting
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run lint

      - name: Run Unit Tests
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run test:ci

      - name: Run e2e Tests
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run e2e:beta

      - name: Prepare Pre-Release
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: |
          git fetch --all
          git config user.name "GitHub Actions"
          git config user.email "yashanand1910@gmail.com"
          npm run release:beta
          git checkout alpha
          git merge beta --allow-unrelated-histories
          git push --follow-tags origin beta
          git push origin alpha

      - name: Build
        if: ${{ !contains(github.event.head_commit.message, 'chore(release)') || !contains(github.event.head_commit.message, '-beta.') }}
        run: npm run build:beta

      - name: Deploy
        if: ${{ !contains(github.event.head_commit.message, 'chore(release)') || !contains(github.event.head_commit.message, '-beta.') }}
        run: npm run deploy:beta -- --token "$FIREBASE_TOKEN"
