name: Pull Request (Alpha)

'on':
  pull_request:
    branches: [alpha]

jobs:
  build_and_preview:
    name: Check & Deploy Preview
    runs-on: ubuntu-latest
    env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2

      - name: Install
        run: npm install

      - name: Check Linting
        run: npm run lint

      - name: Build
        run: npm run build:alpha

      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch_name

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.0
        id: start_deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ steps.extract_branch.outputs.branch }}
          logs: 'https://console.firebase.google.com/u/0/project/rozgar-today/hosting/sites/alpha-rozgar-today'
          ref: ${{ github.head_ref }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy Preview
        id: deployment
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROZGAR_TODAY }}"
          projectId: rozgar-today
          target: alpha
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Finish Deployment
        uses: bobheadxi/deployments@v0.6.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.start_deployment.outputs.deployment_id }}
