name: Pull Request (Alpha)

'on':
  pull_request:
    branches: [alpha]

jobs:
  build_and_preview:
    name: Check & Deploy Preview
    runs-on: macos-latest
    concurrency:
      group: pr-${{ github.head_ref }}
      cancel-in-progress: true
    env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_HOSTING_LOGS_URL: 'https://console.firebase.google.com/u/0/project/rozgar-today/hosting/sites/alpha-rozgar-today'
    steps:
      - uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm ci

      - name: Check Linting
        run: npm run lint

      - name: Start Deployment
        if: "!contains(github.head_ref, 'dependabot')"
        uses: bobheadxi/deployments@v0.6.0
        id: start_deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: "Preview (${{ github.head_ref }})"
          logs: ${{ env.FIREBASE_HOSTING_LOGS_URL }}
          ref: ${{ github.head_ref }}

      - name: Build
        run: npm run build:alpha

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: "!contains(github.head_ref, 'dependabot')"
        name: Deploy Preview
        id: deployment
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROZGAR_TODAY }}"
          projectId: rozgar-today
          target: alpha
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Finish Deployment
        uses: bobheadxi/deployments@v0.6.0
        if: ${{ always() && !contains(github.head_ref, 'dependabot')}}
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          logs: ${{ env.FIREBASE_HOSTING_LOGS_URL }}
          deployment_id: ${{ steps.start_deployment.outputs.deployment_id }}
          env_url: ${{ steps.deployment.outputs.details_url }}
