name: Pull Request (Alpha)

'on':
  pull_request:
    branches: [alpha]

jobs:
  build_and_preview:
    name: Test, Preview & Report Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2

      - name: Install
        run: npm install

      - name: Check Linting
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:ci

      - name: Build
        run: npm run build:alpha

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy Preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROZGAR_TODAY }}'
          projectId: rozgar-today
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v1.0.13
