name: Pull Request (Alpha)

'on':
  pull_request:
    branches: [alpha]

jobs:
  build_and_preview:
    name: Check & Deploy Preview
    runs-on: ubuntu-latest
    env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2

      - name: Install
        run: npm install

      - name: Check Linting
        run: npm run lint

      - name: Build
        run: npm run build:alpha

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy Preview
        id: deployment
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROZGAR_TODAY }}"
          projectId: rozgar-today
          target: alpha
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub Deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ steps.deployment.secrets.GITHUB_TOKEN }}
