name: Test & Deploy Alpha

on:
  push:
    branches: [ master ]

jobs:
  main:
    name: Test & Deploy Alpha
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Install
      run: npm install
    
    - name: Check Linting
      run: npm run lint
    
    - name: Run Unit Tests
      run: npm run test:ci
    
    - name: Build
      run: npm run build:alpha
    
    - name: Deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: npm run deploy:alpha -- --token "$FIREBASE_TOKEN"
